name: Build Velocity 2FA Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # Set up JDK (Velocity supports Java 17+)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Upload plugin jar as an artifact
      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: velocity-2fa-plugin
          path: target/*.jar
